{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Values.namespaces.monitoring }}
  labels:
    {{- include "kubernetes-monitoring.labels" . | nindent 4 }}
    app: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
  - port: {{ .Values.grafana.service.port }}
    targetPort: {{ .Values.grafana.service.port }}
    protocol: TCP
    name: http
    {{- if and (eq .Values.grafana.service.type "NodePort") .Values.grafana.service.nodePort }}
    nodePort: {{ .Values.grafana.service.nodePort }}
    {{- end }}
  selector:
    app: grafana
{{- end }}
